name: wav2vec2-300m-ngram
type: wav2vec2
pretrained_model_id: chcaa/xls-r-300m-danish
freeze_feature_encoder: false

# Model hyperparameters
sampling_rate: 16_000
activation_dropout: 0.1
attention_dropout: 0.1
hidden_dropout: 0.1
feat_proj_dropout: 0.1
final_dropout: 0.1
mask_time_prob: 0.075
mask_feature_prob: 0.075
mask_feature_length: 10
layerdrop: 0.1
ctc_loss_reduction: sum

# Decoder hyperparameters
language_model_decoder: ngram
decoder:
  dataset_id: DDSC/reddit-da-asr-preprocessed
  dataset_subset: null
  dataset_split: train
  n: 5

# Training hyperparameters
batch_size: 8
gradient_accumulation_steps: 4
max_steps: 100_000
learning_rate: 4e-5
warmup_steps: 500
early_stopping: True
early_stopping_patience: 5
fp16: true
eval_steps: 500
save_steps: 500
logging_steps: 100
save_total_limit: 2
