defaults:
  - model: wav2vec2
  - dataset: common_voice_da
  - override hydra/job_logging: custom
  - _self_

dirs:
  data: data
  raw: raw
  processed: processed
  final: final
  models: models

# Model parameters
pipeline_id: ${model.name}-${dataset.name}
hub_id: alexandrainst/${pipeline_id}
model_dir: ${dirs.models}/${pipeline_id}
push_to_hub: false
resume_from_checkpoint: false

# Data parameters
characters_to_keep: 'abcdefghijklmnopqrstuvwxyzæøå0123456789é|'
