defaults:
  - model: wav2vec2
  - dataset: common_voice_da
  - _self_

dirs:
  data: data
  raw: raw
  processed: processed
  final: final

pipeline_id: ${model.name}-${dataset.name}
model_dir: models/${pipeline_id}
push_to_hub: false
resume_from_checkpoint: false
